<?php


use App\lib\Config\Config;
use App\lib\Di\Container;
use PHPUnit\Framework\TestCase;

final class ContainerTest extends TestCase
{

    private Container $container;

    public function setUp(): void
   {
       parent::setUp(); // TODO: Change the autogenerated stub
       $this->container = new Container();
   }

    public function testGet()
    {
        $config =$this->container->get(Config::class);
        $this->assertInstanceOf(Config::class, $config);
    }

    public function testInvalidClass()
    {
        $this->expectException(ReflectionException::class);
        $this->container->get('Invalid Class');
    }
}